### ISSUE TITLE
Time to migrate to Python 3!

### ISSUE THREAD

**Issue by rusefillc** [rusefi/gerbmerge#3]
This repo still uses 2.7 version of Python 

We need to pick migration attempts from the internet and combine with our functional fixes

**Comment by rusefillc** [comment]
Kind of depends https://github.com/rusefi/gerbmerge/issues/4

**Comment by rusefillc** [comment]
See also https://github.com/provideyourown/gerbmerge/issues/8

**Comment by rusefillc** [comment]
Extra info:

there are too many gerbmerge forks. There is a fork with python3 but two problem with it
1) that other fork does not have our fixes, so potentially one can PR all needed fixed into https://github.com/jnicolson/gerbmerge

2) overall I am failing to even start https://github.com/jnicolson/gerbmerge see https://github.com/jnicolson/gerbmerge/issues/10


It could be that the way to go is really to migrate our https://github.com/rusefi/gerbmerge fork to Python 3 as is since that's the safest way to make sure we have all the fixes/changes we need

**Comment by rusefillc** [comment]
we have manual validation tests in https://github.com/rusefi/gerbmerge/tree/rusefi-tests

See also https://github.com/jnicolson/gerbmerge/issues/9

**Comment by andreika-git** [comment]
https://github.com/andreika-git/gerbmerge/commit/f78db83293e9737d4ee4e0d5d377e908ba9aba91
